Events Handlers Branch
Gambit142/Math-Magicians pull request #3
Opened 2021-10-20 20:18 UTC by Gambit142

The Events Handlers Branch contains codes that implemented the following:

> - [ ] Developed the maths logic needed to make the Calculator component work. The codes were gotten from [calculate.js](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/code-samples/calculate.js) and [operate.js](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/code-samples/operate.js)

> - [ ] Handled the `onClick` events for every button in the `Calculator.js` file

> - [ ] Passed `props` from **_parent components_** to  **_children components_**, initialized **_state_**, _**setState**,_ and _**lift state**_

2021-10-20 20:47 UTC, addod19 requested changes
### Hi @Gambit142, 

Good job so far! The operate and calculate are both copied from the recommended source :100: Props passed to child component of the calculate component :1st_place_medal: Application works as expected, all mathematical operations work fine :slightly_smiling_face: Division by zero error handled well :rocket: Git-flow followed :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-20 20:47 UTC, addod19 commented on src/components/Calculator.js
- [ ] It would be better if we import the `calculate.js` logic file from the logic directory. This gives us the flexibility to move logic between components
![Screenshot from 2021-10-20 20-37-37](https://user-images.githubusercontent.com/46388113/138168499-496f46c3-0c83-499d-bb23-a7c1eeddbac0.png)
However, the application works as expected :+1:

2021-10-20 21:12 UTC, addod19 commented on src/components/Calculator.js
Hi @Gambit142, yeah I could see that, but the project guidelines specifically asked to import it in the Calculate component as shown in the screenshot earlier

2021-10-20 21:33 UTC, Gambit142 commented on src/components/Calculator.js
I understand that, but I have to `lift state` and for me to be able to do that, I need to use it in App.js file which contains the `parent` component. If I use the `calculate.js` file in the Calculator component, I will just initialize `state` there and `setState` in the same component and I won't be able to lift state which is also a requirement.

2021-10-21 22:59 UTC, SpaYco commented on src/components/Calculator.js
> +          <button onClick={this.buttonClicked} type="button" className="orange-background">=</button>
- [ ] `[OPTIONAL]` It would be better to [map these](https://coursework.vschool.io/mapping-components-in-react/)

2021-10-22 09:31 UTC, closed without merging